# Generated by Django 4.2.5 on 2023-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('forma_pagamento', models.CharField(choices=[('credito', 'Credito'), ('debito', 'Debito'), ('boleto', 'Boleto')], max_length=10)),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
