# Generated by Django 4.2.5 on 2023-09-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_quantidade_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
