# Generated by Django 4.2.5 on 2023-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
